commit_message: "Crowdin: %original_file_name%の翻訳を更新"
append_commit_message: false
files:
  - source: translations/ja/*.json
    translation: /translations/%two_letters_code%/%file_name%.%file_extension%
